// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUp0lUt-EP3TgnSWPFAj3dl4Zleb4sdI',
    appId: '1:622183970064:web:ad33b2da0fcbddb0b9a195',
    messagingSenderId: '622183970064',
    projectId: 'flutter-auth-d36e8',
    authDomain: 'flutter-auth-d36e8.firebaseapp.com',
    storageBucket: 'flutter-auth-d36e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0MEqFX0lr09GUo4CyK_b69H12kTNpcxM',
    appId: '1:622183970064:android:0d36252bc0eceb73b9a195',
    messagingSenderId: '622183970064',
    projectId: 'flutter-auth-d36e8',
    storageBucket: 'flutter-auth-d36e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMh3L0Or8GYL7oNpghiMw8I06ubDjNZOw',
    appId: '1:622183970064:ios:bb977c919bf827fcb9a195',
    messagingSenderId: '622183970064',
    projectId: 'flutter-auth-d36e8',
    storageBucket: 'flutter-auth-d36e8.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMh3L0Or8GYL7oNpghiMw8I06ubDjNZOw',
    appId: '1:622183970064:ios:f54d4af6dc89a65bb9a195',
    messagingSenderId: '622183970064',
    projectId: 'flutter-auth-d36e8',
    storageBucket: 'flutter-auth-d36e8.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
